language: node_js
sudo: false
node_js:
    - stable
install:
    - npm install
    - export PATH="node_modules/.bin:$PATH"
    - pulp --version
    - bower update
script:
    - pulp build -- +RTS -N1 -RTS
    - pulp test -- +RTS -N1 -RTS
