language: node_js
sudo: false
node_js:
    - stable
install:
    - npm install purescript pulp -g
    - psc --version
    - pulp --version
    - pulp dep update
script:
    - pulp build
    - pulp test
